name: avaleryar


library:
  source-dirs: src
  dependencies:
    - base

    - containers
    - filepath
    - megaparsec
    - mtl
    - qq-literals
    - template-haskell
    - text
    - wl-pprint-text

