name: avaleryar


library:
  source-dirs: src
  dependencies:
    - base

    - containers
    - filepath
    - megaparsec
    - mtl
    - qq-literals
    - template-haskell
    - text
    - wl-pprint-text

tests:
  avaleryar-tests:
    main: Main.hs
    source-dirs: [test]
    dependencies:
      - base 
      - avaleryar

      - hspec
      - hspec-core

      - HUnit
      - QuickCheck
      - directory
      - filepath
      - text
