name: avaleryar
version: 0.0.1

ghc-options:
  - -O2
  - -j4
  - +RTS -A32M -RTS

library:
  source-dirs: src
  dependencies:
    - base

    - containers
    - deepseq
    - filepath
    - hashable
    - megaparsec
    - mtl
    - qq-literals
    - template-haskell
    - text
    - wl-pprint-text

    - logict
    - unordered-containers
    - hashable

tests:
  avaleryar-tests:
    main: Main.hs
    source-dirs: [test]
    dependencies:
      - base
      - avaleryar

      - hspec
      - hspec-core

      - HUnit
      - QuickCheck
      - containers
      - directory
      - filepath
      - text

benchmarks:
  avaleryar-benchmarks:
    main: Main.hs
    source-dirs: [bench]
    dependencies:
      - base
      - avaleryar

      - criterion
      - wl-pprint-text
      - text
