name: avaleryar
version: 0.0.1.1

library:
  source-dirs: src
  dependencies:
    - base

    - containers
    - deepseq
    - filepath
    - hashable
    - megaparsec
    - mtl
    - qq-literals
    - template-haskell
    - text
    - vector
    - wl-pprint-text

tests:
  avaleryar-tests:
    main: Main.hs
    source-dirs: [test]
    build-tools:
      - hspec-discover
    dependencies:
      - base
      - avaleryar

      - hspec
      - hspec-core

      - HUnit
      - QuickCheck
      - containers
      - directory
      - filepath
      - text

benchmarks:
  avaleryar-benchmarks:
    main: Main.hs
    source-dirs: [bench]
    dependencies:
      - base
      - avaleryar

      - criterion
      - wl-pprint-text
      - text
