name: avaleryar-repl
version: 0.0.1.1

library:
  source-dirs: src
  dependencies:
    - base
    - avaleryar

    - containers
    - haskeline
    - mtl
    - optparse-applicative
    - read-editor
    - repline
    - text
    - vector
    - wl-pprint-text

executables:
  avai:
    source-dirs: repl
    main: avai.hs
    dependencies:
      - avaleryar-repl
      - base
