name: avaleryar-extras


library:
  source-dirs: src
  dependencies:
    - base
    - avaleryar

    - aeson
    - attoparsec
    - containers
    - jose-jwt
    - jsonpath
    - mtl
    - postgresql-simple
    - text
    - time
