name: avaleryar-extras
version: 0.0.1

library:
  source-dirs: src
  dependencies:
    - base
    - avaleryar

    - aeson
    - attoparsec
    - containers
    - jose-jwt
    - jsonpath
    - mtl
    - postgresql-simple
    - text
    - time
